# سيؤدي سير العمل هذا إلى تشغيل اختبارات Datadog الاصطناعية داخل مؤسسة Datadog الخاصة بك
# لمزيد من المعلومات حول تشغيل الاختبارات التركيبية ضمن سير عمل GitHub، راجع: https://docs.datadoghq.com/synthetics/cicd_integrations/github_actions/

# يستخدم سير العمل هذا إجراءات غير معتمدة من GitHub.
# يتم توفيرها من قبل طرف ثالث ويحكمها
# شروط خدمة منفصلة وسياسة الخصوصية والدعم
# التوثيق.

#للبدء:

# 1. أضف Datadog API (DD_API_KEY) ومفتاح التطبيق (DD_APP_KEY) كأسرار إلى مستودع GitHub الخاص بك. لمزيد من المعلومات، راجع: https://docs.datadoghq.com/account_management/api-app-keys/.
# 2. ابدأ في استخدام الإجراء ضمن سير العمل الخاص بك

اسم: قم بإجراء اختبارات Datadog الاصطناعية

على:
  يدفع:
    الفروع: [ "رئيسي" ]
  pull_request:
    الفروع: [ "رئيسي" ]

وظائف:
  يبني:
    يعمل على: أوبونتو الأحدث

    خطوات:
    - الاستخدامات: الإجراءات/الخروج@v4

    # قم بإجراء الاختبارات التركيبية ضمن سير عمل GitHub.
    # للحصول على خيارات تكوين إضافية، قم بزيارة الإجراء داخل السوق: https://github.com/marketplace/actions/datadog-synthetics-ci
    - اسم: قم بإجراء اختبارات Datadog الاصطناعية
      الاستخدامات: DataDog/synthetics-ci-github-action@87b505388a22005bb8013481e3f73a367b9a53eb # v1.4.0
      مع:
        api_key: ${{Secrets.DD_API_KEY}}
        app_key: ${{Secrets.DD_APP_KEY}}
        test_search_query: 'علامة:اختبارات e2e' # قم بتعديل هذه العلامة لتناسب استراتيجية وضع العلامات الخاصة بك


